export interface ITradierSymbol {
    ask: number,
    ask_date: number,
    askexch: string,
    asksize: number,
    average_volume: number,
    bid: number,
    bid_date: number,
    bidexch: string,
    bidsize: number,
    change: number,
    change_percentage: number,
    close: number,
    description: string,
    exch: string,
    high: number,
    last: number,
    last_volume: number,
    low: number,
    open: number,
    prevclose: number,
    symbol: string,
    trade_date: Date,
    type: string,
    volume: number,
    week_52_high: number,
    week_52_low: number
}